version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000"
    env_file:
      - .env
#    environment:
#      - DATABASE_URL=postgres://nutriuser:nutripass@db:5432/nutridb
#      - SECRET_KEY=your-secret-key
#      - DEBUG=False
#      - ALLOWED_HOSTS=localhost,127.0.0.1
#      - CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
     - db

  db:
   image: postgres:16-alpine
   env_file:
     - .env
   volumes:
     - nutri_postgres_data:/var/lib/postgresql/data

volumes:
  nutri_postgres_data: